version: "3.8"
services:
  server:
    stdin_open: true
    container_name: ${NAME}
    command: uvicorn src.server.main:app --host 0.0.0.0 --port ${PORT} --debug --reload-dir /app --log-level debug
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - GUNICORN_CMD_ARGS=--reload
    volumes:
      - ./:/app
      - images:/app/src/images
    ports:
      - ${PORT}:${PORT}

volumes:
  images:
    external:
      name: photoanalysisserver_images